#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export BROWSER=chromium
export XDG_CONFIG_HOME="/home/jpfeltracco/.config"
export EDITOR="emacslient -t"
export VISUAL="emacsclient -c -a emacs"
