#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Run fasd with same behavior as autojump
unalias j
alias j="fasd_cd"
alias jj="fasd_cd -i"

# Fix bug with fzf inside neovim terminal - https://github.com/junegunn/fzf/issues/809
[ -n "$NVIM_LISTEN_ADDRESS" ] && export FZF_DEFAULT_OPTS='--no-height'

if [ -n "$NVIM_LISTEN_ADDRESS" ]; then
    export FZF_DEFAULT_OPTS='--no-height'
    export VISUAL="nvr -p"
    alias nvim="$VISUAL"
else
    # unalias nvim
fi

backward-kill-dir () {
    local WORDCHARS=${WORDCHARS/\/}
    zle backward-kill-word
}
zle -N backward-kill-dir
bindkey '^[^?' backward-kill-dir

alias v=$VISUAL

alias f="find . -iname "

alias ssh='TERM=xterm ssh'

xset r rate 200 40
